### ISSUE TITLE
Are you sure the local planner is RRT* ?

### ISSUE THREAD

**Issue by lqywow** [KavitShah1998/Combined_Astar_with_RRTstar_in_ROS#9]

**Comment by KavitShah1998** [comment]
The local planner is not integrated in the main branch.
You can find the source code for RRT* on the branch `SoumyaSrilekhaB-Local_planner_update` here -> https://github.com/KavitShah1998/Autonomous_Mobile_Robot_Navigation_In_ROS/blob/SoumyaSrilekhaB-Local_planner_update/dynamic_obstacle_avoidance/src/Local_Planner.cpp
